moved to new version of combine, OS 9
cms-flaf/Framework pull request #59
Opened 2024-07-12 17:58 UTC by ahmad3213

2024-07-13 05:43 UTC, kandrosov requested changes

2024-07-13 05:43 UTC, kandrosov commented on env.sh
> +  local default_cmssw_ver=CMSSW_13_0_15
why do you roll back to 13_0_15?

2024-07-13 05:43 UTC, kandrosov commented on env.sh
> +    run_cmd bash <(https://raw.githubusercontent.com/nucleosynthesis/work-tools/master/sparse-checkout-SL-ssh.sh)
- please use CombineHarvester from the central repository https://github.com/cms-analysis/CombineHarvester
- It looks like for the newest release, a sparse checkout is not needed, and one can directly use 
  ```
  git clone https://github.com/cms-analysis/CombineHarvester.git CombineHarvester
  ```

2024-07-13 05:43 UTC, kandrosov commented on env.sh
>    alias cmbEnv="env -i HOME=$HOME ANALYSIS_PATH=$ANALYSIS_PATH ANALYSIS_DATA_PATH=$ANALYSIS_DATA_PATH X509_USER_PROXY=$X509_USER_PROXY CENTRAL_STORAGE=$CENTRAL_STORAGE ANALYSIS_BIG_DATA_PATH=$ANALYSI
singularity is no longer needed to run inference

2024-07-15 14:22 UTC, closed without merging

2024-07-15 14:22 UTC, ahmad3213 commented
i mistakenly was pushing new commits to this one. i will open a new PR to avoid confusion taking care of your comments