New tasks patches
cms-flaf/Framework pull request #61
Opened 2024-07-15 14:35 UTC by valeriadamante

This PR is intended to
1. add patches to the previous PR 
2. resolve conflicts with k's PR
3. unify the hist merge + hadd merged task
4. remove ext1

2024-07-16 08:31 UTC, kandrosov requested changes

2024-07-19 07:14 UTC, kandrosov requested changes

2024-07-19 07:14 UTC, kandrosov commented on Analysis/tasks.py
> +import threading
```suggestion
```

2024-07-19 07:38 UTC, valeriadamante commented on config/HH_bbtautau/global.yaml
> +    - 130
yes. I obtained:
```
quantile max (95%) for bb mass resolved =  144.77955932617186
quantile min (95%) for bb mass resolved =  75.6971378326416
quantile max (95%)  for tautau mass resolved =  106.78509750366207
quantile min (95%)  for tautau mass resolved =  35.552077293395996

quantile max (99.5%) for bb mass resolved =  267.4022723388703
quantile min (99.5%) for bb mass resolved =  46.51988693237305
quantile max (99.5%) for tautau mass resolved =  121.6530269622805
quantile min (99.5%) for tautau mass resolved =  23.111099338531496
```

and we went for 20, 130 for tauTau_m_vis

2024-07-19 08:55 UTC, valeriadamante commented on config/HH_bbtautau/global.yaml
> +    - { name: kinFit_m, need_cache: true }
ok

2024-07-19 08:55 UTC, valeriadamante commented on Analysis/tasks.py
> +import threading
ok

2024-07-19 10:45 UTC, kandrosov requested changes

2024-07-19 10:45 UTC, kandrosov commented on Analysis/HistMerger.py
> +        fixNegativeContributions=True
take this from config (same as 'need_cache')

2024-07-19 13:20 UTC, kandrosov approved these changes

2024-07-19 13:20 UTC, merged