Env
cms-flaf/Framework pull request #62
Opened 2024-07-15 15:04 UTC by ahmad3213

Added 2022EE signal samples, combine new version , lumi numbers changed

2024-07-16 08:10 UTC, kandrosov requested changes

2024-07-16 08:10 UTC, kandrosov commented on config/Run3_2022/samples.yaml
> -  sampleType: data
undo modifications to this file

2024-07-16 08:10 UTC, kandrosov commented on env.sh
> +    git clone https://github.com/cms-analysis/CombineHarvester.git CombineHarvester
```suggestion
    run_cmd git clone https://github.com/cms-analysis/CombineHarvester.git CombineHarvester
```

2024-07-16 08:10 UTC, kandrosov commented on env.sh
>    alias cmbEnv="env -i HOME=$HOME ANALYSIS_PATH=$ANALYSIS_PATH ANALYSIS_DATA_PATH=$ANALYSIS_DATA_PATH X509_USER_PROXY=$X509_USER_PROXY CENTRAL_STORAGE=$CENTRAL_STORAGE ANALYSIS_BIG_DATA_PATH=$ANALYSI
```suggestion
  alias cmbEnv="env -i HOME=$HOME ANALYSIS_PATH=$ANALYSIS_PATH ANALYSIS_DATA_PATH=$ANALYSIS_DATA_PATH X509_USER_PROXY=$X509_USER_PROXY CENTRAL_STORAGE=$CENTRAL_STORAGE ANALYSIS_BIG_DATA_PATH=$ANALYSIS_BIG_DATA_PATH $ANALYSIS_PATH/cmb_env.sh"
```

2024-07-24 11:08 UTC, kandrosov commented
@ahmad3213, please resolve conflicts and undo changes to config/Run3_2022/samples.yaml. Once done, the PR is ready to be merged. Thank you!

2024-07-24 11:42 UTC, aebid approved these changes
After cloning, adding this remote, getting this branch, and running source env.sh, I was able to generate the limit plot using previous binning.

2024-07-24 11:50 UTC, ahmad3213 commented
i can open a new PR with exact changes

2024-07-24 11:50 UTC, closed without merging