Bugfix trigger and samples
cms-flaf/Framework pull request #64
Opened 2024-07-15 21:55 UTC by abolshov

quickly fix some bugs

2024-07-15 22:02 UTC, ahmad3213 commented
One commit here which is adding generator in config/Run3_2022/samples.yaml
is also in my PRs ( which is also mot merged)

2024-07-16 08:04 UTC, kandrosov requested changes

2024-07-16 08:04 UTC, kandrosov commented on config/HH_bbWW/Run3_2022/samples.yaml
> +  #crossSection: To_be_added
AnaTuple production will not run without crossSection value. It is expected to be fixed in #63.

2024-07-17 13:52 UTC, ahmad3213 commented
This PR can be closed, all changes here either fixed by #63 or #65

2024-07-17 13:53 UTC, kandrosov commented
- empty triggers case handled in #65
- missing generator entries in #63
closing this PR

2024-07-17 13:53 UTC, closed without merging