Added bbWW Data/MC histogram code
cms-flaf/Framework pull request #81
Opened 2024-10-17 12:37 UTC by aebid

2024-11-13 13:09 UTC, aebid commented
I made a mistake and merged my two branches, so now this PR includes all of the current MuonSF code too ):

I'm working on trying to fix this now

2024-11-22 13:04 UTC, aebid commented
Don't merge yet, I am still checking for any conflicts with a full test

2024-11-22 14:52 UTC, kandrosov requested changes

2024-11-22 15:12 UTC, kandrosov approved these changes

2024-11-26 09:24 UTC, aebid commented
This PR is ready to be reviewed

2024-11-26 12:36 UTC, kandrosov approved these changes

2024-11-26 12:36 UTC, merged