Elec sf
cms-flaf/Framework pull request #88
Opened 2024-12-06 14:56 UTC by ahmad3213

2024-12-11 14:34 UTC, kandrosov requested changes

2024-12-11 14:34 UTC, kandrosov commented on AnaProd/HH_bbWW/baseline.py
> +        v_ops::pt(Electron_p4) > 10 && abs(v_ops::eta(Electron_p4)) < 2.5 && abs(Electron_dz) < 0.1 && abs(Electron_dxy) < 0.05 && Electron_sip3d <= 8 && Electron_miniPFRelIso_all < 0.4 && Electron_m
Can we have 5 GeV at the baseline level to be aligned with muons?

2024-12-11 14:34 UTC, kandrosov commented on config/HH_bbWW/global.yaml
> +  #- pu
```suggestion
  - mu
  - trg
  - ele
  - eleES
  - pu
```

2024-12-11 14:34 UTC, kandrosov commented on config/HH_bbWW/global.yaml
>  channelSelection:
keep all channels on by default

2024-12-11 14:34 UTC, kandrosov commented on config/HH_bbWW/global.yaml
>  channels_to_consider:
keep all channels on by default

2024-12-13 20:46 UTC, kandrosov requested changes
Other items:
- update corrections sub-module

2024-12-15 20:42 UTC, ahmad3213 commented on AnaProd/anaTupleProducer.py
> +        store_noncentral = True
True. It was a hot fix, missed to clean up. I verified customization with the config  works

2025-01-10 14:54 UTC, kandrosov requested changes

2025-01-10 14:54 UTC, kandrosov commented on inference
- don't modify `inference` submodule in this PR
- Point to the latest commit in `main` for `Corrections`

2025-01-17 13:50 UTC, kandrosov approved these changes

2025-01-17 15:38 UTC, merged