Remove requirement of EventsNotSelected
cms-flaf/Framework pull request #89
Opened 2024-12-12 12:42 UTC by aebid

Quick patch of removing EventsNotSelected requirement from anaCache task. Assuming EventsNotSelected is missing due to there being 0 events not selected (from Konstantin), we can replace .Count() with 0.

This problem was in anaCacheProducer AND in Studies/ttHH/selectionEfficiency.py. The selectionEfficiency probably has a poor name if it will be general and not specific to ttHH, but for now this change is required.

2025-01-10 15:54 UTC, kandrosov commented on AnaProd/anaCacheProducer.py
> +            if tree == 'EventsNotSelected' and not has_evt_not_selected: continue
```suggestion
        for tree in [ 'Events', 'EventsNotSelected' ]:
            with ROOT.TFile.Open(input_file) as tmp_file:
                if tree not in tmp_file.GetListOfKeys(): continue
```

2025-01-14 13:07 UTC, aebid commented on AnaProd/anaCacheProducer.py
> +            if tree == 'EventsNotSelected' and not has_evt_not_selected: continue
I'm fine with this as it looks, but isn't it less optimized to open the same file twice compared to what I wrote?

2025-01-14 14:16 UTC, kandrosov commented on AnaProd/anaCacheProducer.py
> +            if tree == 'EventsNotSelected' and not has_evt_not_selected: continue
Yes, it can be optimized more, and you are welcome to do it. But how you wrote it doesn't account for cases where `Events` are missing, so it had to be modified.

2025-01-16 17:20 UTC, kandrosov requested changes

2025-01-16 17:20 UTC, kandrosov commented on AnaProd/anaCacheProducer.py
> +    return events_filelist, eventsNotSelected_filelist
```suggestion
def create_filelists(input_files, keys=['Events', 'EventsNotSelected']):
    file_lists = {}
    for input_file in input_files:
        with ROOT.TFile.Open(input_file) as tmp_file:
            for key in keys:
                if key in tmp_file.GetListOfKeys():
                    if key not in file_lists:
                        file_lists[key] = []
                    file_lists[key].append(input_file)
    return file_lists
```

2025-01-16 17:20 UTC, kandrosov commented on AnaProd/anaCacheProducer.py
> +    anaCache = computeAnaCache(events_filelist, eventsNotSelected_filelist, global_params, args.generator_name,range=args.n_events)
```suggestion
    file_lists = create_filelists(input_files)
    anaCache = computeAnaCache(file_lists, global_params, args.generator_name,range=args.n_events)
```

2025-01-16 17:20 UTC, kandrosov commented on AnaProd/anaCacheProducer.py
> +def computeAnaCache(events_filelist, eventsNotSelected_filelist, global_params, generator, range=None):
```suggestion
def computeAnaCache(file_lists, global_params, generator, range=None):
```

2025-01-16 17:20 UTC, kandrosov commented on AnaProd/anaCacheProducer.py
> +        df = ROOT.RDataFrame(tree, this_filelist)
```suggestion
    for tree, file_list in file_lists.items():
        df = ROOT.RDataFrame(tree, file_list)
```

2025-01-17 09:53 UTC, merged