Fixing Bugs in Plotting with Uncertainties
cms-flaf/Framework pull request #90
Opened 2024-12-12 13:05 UTC by aebid

Look at https://github.com/cms-flaf/Framework/pull/89 first (I don't know how to remove those commits from this PR)

Ignoring first 2 commits, I added some new variables to plotting scripts and fixed some bugs when plotting with HistUncs turned on. Some new datatype support is added but I did not include Muhammad's updates about what datatypes we are saving.

2025-02-14 11:55 UTC, kandrosov approved these changes

2025-02-17 12:31 UTC, aebid commented
We want to remove overlaps with PR #95

So now I need to figure out how to remove any 'anaCache' code from this PR (and it will still be resolved in the next PR anyway)

2025-02-17 13:37 UTC, aebid commented
I do not understand. I removed only 3 commits in a ```git rebase -r -i HEAD~5``` where those 3 commits only changed 3 files. But actually, it seems it changed ~15 files???

2025-02-18 13:05 UTC, aebid commented on config/HH_bbWW/DNN/ResHH_Classifier.keras
Sure, this is from commit #858525f so I'll do the rebase thing again today

2025-02-18 13:08 UTC, aebid commented on include/HistHelper.h
> +typedef std::variant<int,float,bool, unsigned long,unsigned long long,long long, long,unsigned int, RVecI, RVecF,RVecUC,RVecUL,RVecSh,double, unsigned char, kin_fit::FitResults> MultiType;
I undid them with a new commit, but I don't like that the spacing is not consistent. I'm guessing you wanted to undo as it was an unnecessary change

2025-02-18 13:41 UTC, kandrosov commented on include/HistHelper.h
> +typedef std::variant<int,float,bool, unsigned long,unsigned long long,long long, long,unsigned int, RVecI, RVecF,RVecUC,RVecUL,RVecSh,double, unsigned char, kin_fit::FitResults> MultiType;
When some logic in the file needs to be modified, I am fine with you fixing the spacing. But if it is the only modification in the file, this doesn't sound right because it unnecessarily complicates modification history.

2025-02-18 13:43 UTC, kandrosov requested changes

2025-02-18 13:43 UTC, kandrosov commented on config/HH_bbWW/DNN/ResHH_Classifier.keras
GitHub shows that it is still present...

2025-02-18 13:48 UTC, aebid commented on config/HH_bbWW/DNN/ResHH_Classifier.keras
I'm confused I just made a commit to change them and now the old request says outdated

2025-02-18 13:50 UTC, aebid commented on config/HH_bbWW/DNN/ResHH_Classifier.keras
Oh wait yeah this one was not fixed yet because this is rebase

2025-02-19 11:07 UTC, kandrosov approved these changes

2025-02-19 11:08 UTC, merged